name: Olympic Medal Updater

on:
  # schedule:
  #   # 8:00 AM CST = 14:00 UTC
  #   # 8:00 PM CST = 02:00 UTC (Next Day)
  #   - cron: '0 14 * * *'
  #   - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual trigger from Actions tab

permissions:
  contents: write

jobs:
  update-medals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Updater Script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python main.py

    - name: Commit Data Files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.json *.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scraped datasets and hardware CSV" && git push)
